---
- name: add user and permission 
  hosts: all

  tasks:
    - name: configure sshd_config
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication no$' 
        line: PasswordAuthentication yes 
      become: yes

    - name: restart sshd 
      ansible.builtin.service:
        name: sshd
        state: restarted
      become: yes

    - name: configure subscriptions
      community.general.redhat_subscription:
        state: present
        username: "{{ redhat_subscription_username }}"
        password: "{{ redhat_subscription_password }}"
        auto_attach: true
      become: yes
