---
- name: kube test
  hosts: tower1

  tasks:
    - name: role-pxbackup/task-install-pxbackup.yml/Install PX Backup Chart
      #community.kubernetes.helm:
      kubernetes.core.helm:
        name: px-central
        #create_namespace: true
        release_namespace: px-backup
        chart_ref: portworx/px-central
        #chart_version: "{{ pxbkupversion }}"
        #release_values:
        values:
          pxbackup:
            enabled: true
          persistentStorage:
            enabled: true
            storageClassName: test
