---
- name: test
  hosts: ec2-35-161-131-63.us-west-2.compute.amazonaws.com
  gather_facts: no
  become: true

  tasks:
          # - name: install lvm2 binaries
          #   command: '/usr/bin/yum install -y lvm2'
          #   retries: 10
          #   delay: 2
          #   async: 60
          #   poll: 5

    - name: try the yum module
      yum:
        name: lvm2
        state: absent
