- name: get date
  ansible.builtin.shell: date +%Y-%m-%d 
  register: today

- name: check subscription is not already attached
  ansible.builtin.shell:
    cmd: subscription-manager list --consumed | grep -c "{{ subscription_search }}" || /bin/true
  register: attached
  become: yes 

- name: collect relavant pool id
  ansible.builtin.shell:
    cmd: subscription-manager list --available --all --matches="{{ subscription_search }}" --pool --ondate="{{ today.stdout }}" | head -n 1
  register: pool_id
  become: yes 
  when: attached.stdout|int == 0

- name: register "{{ pool_id.stdout }}"
  community.general.redhat_subscription:
    state: present
    username: "{{ redhat_subscription_username }}"
    password: "{{ redhat_subscription_password }}"
    pool_ids: "{{ pool_id.stdout }}"
  become: yes
  when: attached.stdout|int == 0
